/**
 * Scene Manifest Matrix - Warm Pediatric Healthcare Identity
 * Clean, White/Off-White, Minimal, Trustworthy Palette
 */

export const SCENE_IDS = {
  SPLASH: 'scene_splash',
  HIDDEN_REALITY: 'scene_hidden_reality',
  GROWTH_INTELLIGENCE: 'scene_growth_intelligence',
  PEDIATRIC_AI: 'scene_pediatric_ai',
  MEDICAL_TRUST: 'scene_medical_trust',
  KIDS_UNIVERSE: 'scene_kids_universe',
  LANDING_REVEAL: 'scene_landing_reveal',
};

export const SCENE_MANIFEST = [
  {
    id: SCENE_IDS.SPLASH,
    stepIndex: 0,
    title: 'Preloader & Brand Entrance',
    camera: { x: 0, y: 0, z: 0, rotateX: 0, rotateY: 0, zoom: 1, blur: 0 },
    palette: {
      primary: '#FFFFFF',
      surface: '#F8FAFC',
      secondary: '#2563EB',
      glow: '#22C55E',
      accent: '#F59E0B',
      text: '#0F172A',
      muted: '#64748B',
    },
    particleMode: 'SOFT_NUTRITION_DOTS',
    assets: ['/logo.png', '/indian_food.jpg', '/digital_twin.png', '/doctor_safety.png', '/gamified_kids.png'],
  },
  {
    id: SCENE_IDS.HIDDEN_REALITY,
    stepIndex: 1,
    title: 'Step 01 • Hidden Reality',
    camera: { x: 0, y: 0, z: 0, rotateX: 0, rotateY: 0, zoom: 1, blur: 0 },
    palette: {
      primary: '#FFFFFF',
      surface: '#F8FAFC',
      secondary: '#2563EB',
      glow: '#22C55E',
      accent: '#F59E0B',
      text: '#0F172A',
      muted: '#64748B',
    },
    particleMode: 'MEAL_SCAN_ORBS',
    assets: ['/indian_food.jpg'],
  },
  {
    id: SCENE_IDS.GROWTH_INTELLIGENCE,
    stepIndex: 2,
    title: 'Step 02 • Future Vision',
    camera: { x: 0, y: 0, z: 0, rotateX: 0, rotateY: 0, zoom: 1, blur: 0 },
    palette: {
      primary: '#FFFFFF',
      surface: '#F8FAFC',
      secondary: '#2563EB',
      glow: '#22C55E',
      accent: '#F59E0B',
      text: '#0F172A',
      muted: '#64748B',
    },
    particleMode: 'GROWTH_TRAJECTORY',
    assets: ['/digital_twin.png'],
  },
  {
    id: SCENE_IDS.PEDIATRIC_AI,
    stepIndex: 3,
    title: 'Step 03 • Pediatric AI Engine',
    camera: { x: 0, y: 0, z: 0, rotateX: 0, rotateY: 0, zoom: 1, blur: 0 },
    palette: {
      primary: '#FFFFFF',
      surface: '#F8FAFC',
      secondary: '#2563EB',
      glow: '#22C55E',
      accent: '#F59E0B',
      text: '#0F172A',
      muted: '#64748B',
    },
    particleMode: 'NEURAL_MATRIX',
    assets: [],
  },
  {
    id: SCENE_IDS.MEDICAL_TRUST,
    stepIndex: 4,
    title: 'Step 04 • Clinical Trust Network',
    camera: { x: 0, y: 0, z: 0, rotateX: 0, rotateY: 0, zoom: 1, blur: 0 },
    palette: {
      primary: '#FFFFFF',
      surface: '#F8FAFC',
      secondary: '#2563EB',
      glow: '#22C55E',
      accent: '#F59E0B',
      text: '#0F172A',
      muted: '#64748B',
    },
    particleMode: 'DNA_HELIX',
    assets: ['/doctor_safety.png'],
  },
  {
    id: SCENE_IDS.KIDS_UNIVERSE,
    stepIndex: 5,
    title: 'Step 05 • Living Kids Universe',
    camera: { x: 0, y: 0, z: 0, rotateX: 0, rotateY: 0, zoom: 1, blur: 0 },
    palette: {
      primary: '#FFFFFF',
      surface: '#F8FAFC',
      secondary: '#2563EB',
      glow: '#22C55E',
      accent: '#F59E0B',
      text: '#0F172A',
      muted: '#64748B',
    },
    particleMode: 'FLOATING_QUESTS',
    assets: ['/gamified_kids.png'],
  },
  {
    id: SCENE_IDS.LANDING_REVEAL,
    stepIndex: 6,
    title: 'Welcome to NutriKids',
    camera: { x: 0, y: 0, z: 0, rotateX: 0, rotateY: 0, zoom: 1, blur: 0 },
    palette: {
      primary: '#FFFFFF',
      surface: '#F8FAFC',
      secondary: '#2563EB',
      glow: '#22C55E',
      accent: '#F59E0B',
      text: '#0F172A',
      muted: '#64748B',
    },
    particleMode: 'SYNTHESIS_BURST',
    assets: [],
  },
];
