// Pediatric Nutrition Engine based on IFCT 2017 and USDA databases.
// Maps foods to Calories, Protein, Carbohydrates, Fat, Fiber, Iron, Calcium, and Vitamin C.
// AUTO-GENERATED from frontend/src/data/foodDatabase.js - Do not edit manually.

export const NUTRITION_DB = {
    "water": {
        name: "Water",
        servingSize: "1 glass (250ml)",
        calories: 0,
        protein: 0,
        carbs: 0,
        fat: 0,
        fiber: 0,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "idli": {
        name: "Idli",
        servingSize: "1 piece",
        calories: 60,
        protein: 2,
        carbs: 12,
        fat: 0.2,
        fiber: 1,
        iron: 0.4,
        calcium: 10,
        vitaminC: 0
    },
    "mini idli": {
        name: "Mini Idli",
        servingSize: "1 plate (10 pieces)",
        calories: 150,
        protein: 4,
        carbs: 30,
        fat: 0.5,
        fiber: 2,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "rava idli": {
        name: "Rava Idli",
        servingSize: "1 piece",
        calories: 90,
        protein: 3,
        carbs: 18,
        fat: 1,
        fiber: 1.2,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "sambar idli": {
        name: "Sambar Idli",
        servingSize: "1 plate (2 pieces)",
        calories: 240,
        protein: 7,
        carbs: 45,
        fat: 4,
        fiber: 5,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "plain dosa": {
        name: "Plain Dosa",
        servingSize: "1 medium",
        calories: 130,
        protein: 3,
        carbs: 22,
        fat: 4,
        fiber: 1.5,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "masala dosa": {
        name: "Masala Dosa",
        servingSize: "1 medium",
        calories: 350,
        protein: 6,
        carbs: 45,
        fat: 15,
        fiber: 3,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "rava dosa": {
        name: "Rava Dosa",
        servingSize: "1 medium",
        calories: 180,
        protein: 4,
        carbs: 32,
        fat: 8,
        fiber: 1.5,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "onion dosa": {
        name: "Onion Dosa",
        servingSize: "1 medium",
        calories: 160,
        protein: 4,
        carbs: 26,
        fat: 6,
        fiber: 2,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "pesarattu": {
        name: "Pesarattu",
        servingSize: "1 medium",
        calories: 180,
        protein: 8,
        carbs: 24,
        fat: 5,
        fiber: 4,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "uttapam": {
        name: "Uttapam",
        servingSize: "1 medium",
        calories: 200,
        protein: 5,
        carbs: 30,
        fat: 6,
        fiber: 2.5,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "ven pongal": {
        name: "Ven Pongal",
        servingSize: "1 bowl",
        calories: 250,
        protein: 6,
        carbs: 40,
        fat: 8,
        fiber: 3,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "rava upma": {
        name: "Rava Upma",
        servingSize: "1 bowl",
        calories: 220,
        protein: 4,
        carbs: 30,
        fat: 8,
        fiber: 2,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "aval upma": {
        name: "Aval Upma",
        servingSize: "1 bowl",
        calories: 200,
        protein: 3,
        carbs: 35,
        fat: 7,
        fiber: 2.5,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "puttu": {
        name: "Puttu",
        servingSize: "1 cup",
        calories: 240,
        protein: 5,
        carbs: 50,
        fat: 3,
        fiber: 2,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "appam": {
        name: "Appam",
        servingSize: "1 piece",
        calories: 120,
        protein: 2,
        carbs: 20,
        fat: 3,
        fiber: 1,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "idiyappam": {
        name: "Idiyappam",
        servingSize: "2 pieces",
        calories: 140,
        protein: 3,
        carbs: 30,
        fat: 0.5,
        fiber: 1,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "kozhukattai": {
        name: "Kozhukattai",
        servingSize: "2 pieces",
        calories: 180,
        protein: 3,
        carbs: 38,
        fat: 2,
        fiber: 1.5,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "medu vada": {
        name: "Medu Vada",
        servingSize: "1 piece",
        calories: 95,
        protein: 3,
        carbs: 8,
        fat: 6,
        fiber: 1.5,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "paruppu vada": {
        name: "Paruppu Vada",
        servingSize: "1 piece",
        calories: 80,
        protein: 2.5,
        carbs: 10,
        fat: 4.5,
        fiber: 2,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "aloo paratha": {
        name: "Aloo Paratha",
        servingSize: "1 medium",
        calories: 210,
        protein: 5,
        carbs: 32,
        fat: 8,
        fiber: 3,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "gobi paratha": {
        name: "Gobi Paratha",
        servingSize: "1 medium",
        calories: 190,
        protein: 5,
        carbs: 28,
        fat: 7,
        fiber: 3,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "paneer paratha": {
        name: "Paneer Paratha",
        servingSize: "1 medium",
        calories: 260,
        protein: 9,
        carbs: 28,
        fat: 12,
        fiber: 3,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "methi paratha": {
        name: "Methi Paratha",
        servingSize: "1 medium",
        calories: 170,
        protein: 4,
        carbs: 24,
        fat: 6,
        fiber: 3.5,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "plain paratha": {
        name: "Plain Paratha",
        servingSize: "1 medium",
        calories: 180,
        protein: 4,
        carbs: 25,
        fat: 8,
        fiber: 2,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "poori": {
        name: "Poori",
        servingSize: "1 piece",
        calories: 100,
        protein: 2,
        carbs: 12,
        fat: 5,
        fiber: 1,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "bhatura": {
        name: "Bhatura",
        servingSize: "1 piece",
        calories: 280,
        protein: 6,
        carbs: 42,
        fat: 12,
        fiber: 1.5,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "chole bhature": {
        name: "Chole Bhature",
        servingSize: "1 plate",
        calories: 650,
        protein: 18,
        carbs: 90,
        fat: 28,
        fiber: 8,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "stuffed kulcha": {
        name: "Stuffed Kulcha",
        servingSize: "1 piece",
        calories: 240,
        protein: 6,
        carbs: 38,
        fat: 8,
        fiber: 2.5,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "poha": {
        name: "Poha",
        servingSize: "1 bowl",
        calories: 200,
        protein: 3,
        carbs: 35,
        fat: 7,
        fiber: 2.5,
        iron: 2.5,
        calcium: 15,
        vitaminC: 5
    },
    "sabudana khichdi": {
        name: "Sabudana Khichdi",
        servingSize: "1 bowl",
        calories: 280,
        protein: 3,
        carbs: 55,
        fat: 8,
        fiber: 2,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "bread butter": {
        name: "Bread Butter",
        servingSize: "2 slices",
        calories: 180,
        protein: 5,
        carbs: 24,
        fat: 8,
        fiber: 1.5,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "bread jam": {
        name: "Bread Jam",
        servingSize: "2 slices",
        calories: 170,
        protein: 4,
        carbs: 32,
        fat: 3,
        fiber: 1.5,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "bread omelette": {
        name: "Bread Omelette",
        servingSize: "1 serving",
        calories: 250,
        protein: 11,
        carbs: 25,
        fat: 12,
        fiber: 2,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "omelette": {
        name: "Omelette",
        servingSize: "1 egg",
        calories: 110,
        protein: 7,
        carbs: 1,
        fat: 8,
        fiber: 0,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "boiled egg": {
        name: "Boiled Egg",
        servingSize: "1 large",
        calories: 78,
        protein: 6,
        carbs: 1,
        fat: 5,
        fiber: 0,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "scrambled egg": {
        name: "Scrambled Egg",
        servingSize: "2 eggs",
        calories: 180,
        protein: 14,
        carbs: 3,
        fat: 12,
        fiber: 0,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "cornflakes": {
        name: "Cornflakes",
        servingSize: "1 bowl with milk",
        calories: 200,
        protein: 7,
        carbs: 35,
        fat: 4,
        fiber: 1.5,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "oats": {
        name: "Oats",
        servingSize: "1 bowl with milk",
        calories: 180,
        protein: 6,
        carbs: 28,
        fat: 5,
        fiber: 4,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "muesli": {
        name: "Muesli",
        servingSize: "1 bowl with milk",
        calories: 280,
        protein: 9,
        carbs: 40,
        fat: 8,
        fiber: 5,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "milk": {
        name: "Milk",
        servingSize: "1 glass",
        calories: 150,
        protein: 8,
        carbs: 12,
        fat: 8,
        fiber: 0,
        iron: 0.1,
        calcium: 300,
        vitaminC: 1
    },
    "banana milkshake": {
        name: "Banana Milkshake",
        servingSize: "1 glass",
        calories: 220,
        protein: 6,
        carbs: 38,
        fat: 6,
        fiber: 3,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "fruit bowl": {
        name: "Fruit Bowl",
        servingSize: "1 bowl",
        calories: 120,
        protein: 1.5,
        carbs: 28,
        fat: 0.5,
        fiber: 4.5,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "white rice": {
        name: "White Rice",
        servingSize: "1 bowl",
        calories: 200,
        protein: 4,
        carbs: 44,
        fat: 0.5,
        fiber: 0.6,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "brown rice": {
        name: "Brown Rice",
        servingSize: "1 bowl",
        calories: 215,
        protein: 5,
        carbs: 45,
        fat: 1.6,
        fiber: 3.5,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "red rice": {
        name: "Red Rice",
        servingSize: "1 bowl",
        calories: 210,
        protein: 4.5,
        carbs: 44,
        fat: 1.5,
        fiber: 4,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "jeera rice": {
        name: "Jeera Rice",
        servingSize: "1 bowl",
        calories: 220,
        protein: 4,
        carbs: 40,
        fat: 5,
        fiber: 1,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "lemon rice": {
        name: "Lemon Rice",
        servingSize: "1 bowl",
        calories: 260,
        protein: 5,
        carbs: 42,
        fat: 8,
        fiber: 2,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "coconut rice": {
        name: "Coconut Rice",
        servingSize: "1 bowl",
        calories: 280,
        protein: 4.5,
        carbs: 42,
        fat: 11,
        fiber: 2.5,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "tomato rice": {
        name: "Tomato Rice",
        servingSize: "1 bowl",
        calories: 240,
        protein: 4,
        carbs: 40,
        fat: 7,
        fiber: 2.2,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "tamarind rice": {
        name: "Tamarind Rice",
        servingSize: "1 bowl",
        calories: 250,
        protein: 4,
        carbs: 44,
        fat: 7,
        fiber: 2.5,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "curd rice": {
        name: "Curd Rice",
        servingSize: "1 bowl",
        calories: 280,
        protein: 8,
        carbs: 40,
        fat: 10,
        fiber: 1,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "vegetable rice": {
        name: "Vegetable Rice",
        servingSize: "1 bowl",
        calories: 240,
        protein: 5,
        carbs: 42,
        fat: 6,
        fiber: 3.5,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "ghee rice": {
        name: "Ghee Rice",
        servingSize: "1 bowl",
        calories: 290,
        protein: 4.5,
        carbs: 40,
        fat: 13,
        fiber: 1,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "puliyodarai": {
        name: "Puliyodarai",
        servingSize: "1 bowl",
        calories: 250,
        protein: 4,
        carbs: 44,
        fat: 7,
        fiber: 2.5,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "bisi bele bath": {
        name: "Bisi Bele Bath",
        servingSize: "1 bowl",
        calories: 280,
        protein: 8,
        carbs: 45,
        fat: 8,
        fiber: 4,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "sambar": {
        name: "Sambar",
        servingSize: "1 bowl",
        calories: 160,
        protein: 5,
        carbs: 25,
        fat: 4,
        fiber: 4,
        iron: 1.5,
        calcium: 30,
        vitaminC: 4
    },
    "rasam": {
        name: "Rasam",
        servingSize: "1 bowl",
        calories: 80,
        protein: 1,
        carbs: 10,
        fat: 3,
        fiber: 1,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "dal fry": {
        name: "Dal Fry",
        servingSize: "1 bowl",
        calories: 180,
        protein: 8,
        carbs: 22,
        fat: 7,
        fiber: 4,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "dal tadka": {
        name: "Dal Tadka",
        servingSize: "1 bowl",
        calories: 190,
        protein: 8,
        carbs: 22,
        fat: 8,
        fiber: 4,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "moong dal": {
        name: "Moong Dal",
        servingSize: "1 bowl",
        calories: 140,
        protein: 8,
        carbs: 18,
        fat: 3,
        fiber: 3.5,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "toor dal": {
        name: "Toor Dal",
        servingSize: "1 bowl",
        calories: 150,
        protein: 7,
        carbs: 20,
        fat: 4,
        fiber: 4,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "rajma": {
        name: "Rajma",
        servingSize: "1 bowl",
        calories: 240,
        protein: 10,
        carbs: 30,
        fat: 8,
        fiber: 6,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "chole": {
        name: "Chole",
        servingSize: "1 bowl",
        calories: 250,
        protein: 11,
        carbs: 32,
        fat: 9,
        fiber: 6,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "kadhi": {
        name: "Kadhi",
        servingSize: "1 bowl",
        calories: 130,
        protein: 4,
        carbs: 15,
        fat: 6,
        fiber: 1,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "mixed dal": {
        name: "Mixed Dal",
        servingSize: "1 bowl",
        calories: 170,
        protein: 9,
        carbs: 20,
        fat: 5,
        fiber: 5,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "potato curry": {
        name: "Potato Curry",
        servingSize: "1 bowl",
        calories: 180,
        protein: 3,
        carbs: 28,
        fat: 6,
        fiber: 3,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "cabbage curry": {
        name: "Cabbage Curry",
        servingSize: "1 bowl",
        calories: 100,
        protein: 3,
        carbs: 15,
        fat: 4,
        fiber: 3.2,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "beans curry": {
        name: "Beans Curry",
        servingSize: "1 bowl",
        calories: 110,
        protein: 3,
        carbs: 12,
        fat: 5,
        fiber: 4,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "carrot curry": {
        name: "Carrot Curry",
        servingSize: "1 bowl",
        calories: 110,
        protein: 2,
        carbs: 16,
        fat: 5,
        fiber: 3.8,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "beetroot curry": {
        name: "Beetroot Curry",
        servingSize: "1 bowl",
        calories: 120,
        protein: 2,
        carbs: 18,
        fat: 5,
        fiber: 4,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "brinjal curry": {
        name: "Brinjal Curry",
        servingSize: "1 bowl",
        calories: 130,
        protein: 2,
        carbs: 14,
        fat: 8,
        fiber: 3,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "ladies finger curry": {
        name: "Ladies Finger Curry",
        servingSize: "1 bowl",
        calories: 120,
        protein: 3,
        carbs: 12,
        fat: 7,
        fiber: 3.5,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "pumpkin curry": {
        name: "Pumpkin Curry",
        servingSize: "1 bowl",
        calories: 110,
        protein: 2,
        carbs: 14,
        fat: 6,
        fiber: 3,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "mixed vegetable curry": {
        name: "Mixed Vegetable Curry",
        servingSize: "1 bowl",
        calories: 150,
        protein: 3,
        carbs: 18,
        fat: 7,
        fiber: 4,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "cauliflower curry": {
        name: "Cauliflower Curry",
        servingSize: "1 bowl",
        calories: 120,
        protein: 4,
        carbs: 14,
        fat: 6,
        fiber: 3.5,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "peas curry": {
        name: "Peas Curry",
        servingSize: "1 bowl",
        calories: 150,
        protein: 6,
        carbs: 20,
        fat: 5,
        fiber: 5,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "paneer curry": {
        name: "Paneer Curry",
        servingSize: "1 bowl",
        calories: 280,
        protein: 14,
        carbs: 10,
        fat: 20,
        fiber: 1,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "egg curry": {
        name: "Egg Curry",
        servingSize: "1 bowl",
        calories: 220,
        protein: 14,
        carbs: 8,
        fat: 14,
        fiber: 1,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "chicken curry": {
        name: "Chicken Curry",
        servingSize: "1 bowl",
        calories: 280,
        protein: 25,
        carbs: 8,
        fat: 15,
        fiber: 1.5,
        iron: 2.2,
        calcium: 30,
        vitaminC: 2
    },
    "chicken roast": {
        name: "Chicken Roast",
        servingSize: "1 plate",
        calories: 320,
        protein: 28,
        carbs: 5,
        fat: 20,
        fiber: 1,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "chicken fry": {
        name: "Chicken Fry",
        servingSize: "1 piece",
        calories: 180,
        protein: 15,
        carbs: 4,
        fat: 12,
        fiber: 0.5,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "fish curry": {
        name: "Fish Curry",
        servingSize: "1 bowl",
        calories: 250,
        protein: 20,
        carbs: 6,
        fat: 15,
        fiber: 1,
        iron: 1.8,
        calcium: 45,
        vitaminC: 3
    },
    "fish fry": {
        name: "Fish Fry",
        servingSize: "1 piece",
        calories: 200,
        protein: 18,
        carbs: 5,
        fat: 12,
        fiber: 0.5,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "mutton curry": {
        name: "Mutton Curry",
        servingSize: "1 bowl",
        calories: 350,
        protein: 28,
        carbs: 5,
        fat: 22,
        fiber: 1,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "soya chunks curry": {
        name: "Soya Chunks Curry",
        servingSize: "1 bowl",
        calories: 180,
        protein: 18,
        carbs: 15,
        fat: 6,
        fiber: 6,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "curd": {
        name: "Curd",
        servingSize: "1 cup",
        calories: 100,
        protein: 5,
        carbs: 6,
        fat: 6,
        fiber: 0,
        iron: 0.1,
        calcium: 150,
        vitaminC: 0.5
    },
    "buttermilk": {
        name: "Buttermilk",
        servingSize: "1 glass",
        calories: 40,
        protein: 2,
        carbs: 3,
        fat: 2,
        fiber: 0,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "pickle": {
        name: "Pickle",
        servingSize: "1 teaspoon",
        calories: 15,
        protein: 0.2,
        carbs: 1,
        fat: 1,
        fiber: 0.2,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "papad": {
        name: "Papad",
        servingSize: "1 piece",
        calories: 35,
        protein: 1,
        carbs: 6,
        fat: 0.5,
        fiber: 0.5,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "salad": {
        name: "Salad",
        servingSize: "1 cup",
        calories: 35,
        protein: 1,
        carbs: 7,
        fat: 0,
        fiber: 3,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "chapati": {
        name: "Chapati",
        servingSize: "1 medium",
        calories: 104,
        protein: 3,
        carbs: 22,
        fat: 0.5,
        fiber: 2.5,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "phulka": {
        name: "Phulka",
        servingSize: "1 medium",
        calories: 80,
        protein: 2.5,
        carbs: 17,
        fat: 0.2,
        fiber: 2,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "roti": {
        name: "Roti",
        servingSize: "1 medium",
        calories: 104,
        protein: 3,
        carbs: 22,
        fat: 0.5,
        fiber: 2.5,
        iron: 1.2,
        calcium: 15,
        vitaminC: 0
    },
    "multigrain roti": {
        name: "Multigrain Roti",
        servingSize: "1 medium",
        calories: 110,
        protein: 4,
        carbs: 20,
        fat: 1,
        fiber: 4,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "bajra roti": {
        name: "Bajra Roti",
        servingSize: "1 medium",
        calories: 120,
        protein: 3.5,
        carbs: 24,
        fat: 1.5,
        fiber: 3.5,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "jowar roti": {
        name: "Jowar Roti",
        servingSize: "1 medium",
        calories: 115,
        protein: 3,
        carbs: 24,
        fat: 1.2,
        fiber: 3,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "paneer sabzi": {
        name: "Paneer Sabzi",
        servingSize: "1 bowl",
        calories: 260,
        protein: 13,
        carbs: 8,
        fat: 20,
        fiber: 1,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "aloo sabzi": {
        name: "Aloo Sabzi",
        servingSize: "1 bowl",
        calories: 160,
        protein: 3,
        carbs: 25,
        fat: 6,
        fiber: 3,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "mixed vegetable sabzi": {
        name: "Mixed Vegetable Sabzi",
        servingSize: "1 bowl",
        calories: 140,
        protein: 3,
        carbs: 16,
        fat: 6,
        fiber: 4.5,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "vegetable khichdi": {
        name: "Vegetable Khichdi",
        servingSize: "1 bowl",
        calories: 220,
        protein: 6,
        carbs: 38,
        fat: 5,
        fiber: 4,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "soup": {
        name: "Soup",
        servingSize: "1 bowl",
        calories: 80,
        protein: 2,
        carbs: 12,
        fat: 2,
        fiber: 3,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "vegetable soup": {
        name: "Vegetable Soup",
        servingSize: "1 bowl",
        calories: 75,
        protein: 2,
        carbs: 11,
        fat: 2,
        fiber: 3,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "tomato soup": {
        name: "Tomato Soup",
        servingSize: "1 bowl",
        calories: 90,
        protein: 1.5,
        carbs: 14,
        fat: 3,
        fiber: 2,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "banana": {
        name: "Banana",
        servingSize: "1 medium",
        calories: 105,
        protein: 1,
        carbs: 27,
        fat: 0.3,
        fiber: 3,
        iron: 0.3,
        calcium: 6,
        vitaminC: 10
    },
    "apple": {
        name: "Apple",
        servingSize: "1 medium",
        calories: 95,
        protein: 0.5,
        carbs: 25,
        fat: 0.3,
        fiber: 4.4,
        iron: 0.2,
        calcium: 10,
        vitaminC: 8.4
    },
    "orange": {
        name: "Orange",
        servingSize: "1 medium",
        calories: 60,
        protein: 1.2,
        carbs: 15,
        fat: 0.2,
        fiber: 3,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "guava": {
        name: "Guava",
        servingSize: "1 medium",
        calories: 40,
        protein: 2,
        carbs: 10,
        fat: 0.5,
        fiber: 5,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "papaya": {
        name: "Papaya",
        servingSize: "1 cup",
        calories: 55,
        protein: 0.6,
        carbs: 14,
        fat: 0.2,
        fiber: 2.5,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "watermelon": {
        name: "Watermelon",
        servingSize: "1 slice",
        calories: 45,
        protein: 1,
        carbs: 11,
        fat: 0.2,
        fiber: 0.6,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "pomegranate": {
        name: "Pomegranate",
        servingSize: "1 cup",
        calories: 83,
        protein: 1.7,
        carbs: 19,
        fat: 1.2,
        fiber: 4,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "grapes": {
        name: "Grapes",
        servingSize: "1 cup",
        calories: 62,
        protein: 0.6,
        carbs: 16,
        fat: 0.3,
        fiber: 1,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "mango": {
        name: "Mango",
        servingSize: "1 medium",
        calories: 150,
        protein: 1.5,
        carbs: 35,
        fat: 0.5,
        fiber: 2.6,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "pear": {
        name: "Pear",
        servingSize: "1 medium",
        calories: 100,
        protein: 0.6,
        carbs: 26,
        fat: 0.2,
        fiber: 5,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "almonds": {
        name: "Almonds",
        servingSize: "10 pieces",
        calories: 70,
        protein: 2.5,
        carbs: 2.5,
        fat: 6,
        fiber: 1.2,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "cashews": {
        name: "Cashews",
        servingSize: "10 pieces",
        calories: 80,
        protein: 2,
        carbs: 4,
        fat: 6,
        fiber: 0.5,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "walnuts": {
        name: "Walnuts",
        servingSize: "4 halves",
        calories: 100,
        protein: 2.5,
        carbs: 2,
        fat: 10,
        fiber: 1,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "pistachios": {
        name: "Pistachios",
        servingSize: "15 pieces",
        calories: 80,
        protein: 3,
        carbs: 4,
        fat: 6,
        fiber: 1,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "raisins": {
        name: "Raisins",
        servingSize: "1 tbsp",
        calories: 40,
        protein: 0.5,
        carbs: 11,
        fat: 0.1,
        fiber: 0.5,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "dates": {
        name: "Dates",
        servingSize: "2 pieces",
        calories: 130,
        protein: 1,
        carbs: 30,
        fat: 0.2,
        fiber: 3,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "sundal": {
        name: "Sundal",
        servingSize: "1 bowl",
        calories: 180,
        protein: 8,
        carbs: 22,
        fat: 6,
        fiber: 5,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "roasted chana": {
        name: "Roasted Chana",
        servingSize: "1 handful",
        calories: 120,
        protein: 7,
        carbs: 18,
        fat: 2,
        fiber: 4,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "peanut chikki": {
        name: "Peanut Chikki",
        servingSize: "1 piece",
        calories: 150,
        protein: 4,
        carbs: 18,
        fat: 7,
        fiber: 1.5,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "murukku": {
        name: "Murukku",
        servingSize: "1 piece",
        calories: 120,
        protein: 2,
        carbs: 18,
        fat: 5,
        fiber: 0.5,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "mixture": {
        name: "Mixture",
        servingSize: "1 cup",
        calories: 240,
        protein: 5,
        carbs: 28,
        fat: 12,
        fiber: 1,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "khakhra": {
        name: "Khakhra",
        servingSize: "1 piece",
        calories: 80,
        protein: 2.5,
        carbs: 14,
        fat: 1.5,
        fiber: 1,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "dhokla": {
        name: "Dhokla",
        servingSize: "4 pieces",
        calories: 160,
        protein: 6,
        carbs: 20,
        fat: 6,
        fiber: 1.5,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "biscuits": {
        name: "Biscuits",
        servingSize: "2 pieces",
        calories: 80,
        protein: 1,
        carbs: 14,
        fat: 3,
        fiber: 0.5,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "cookies": {
        name: "Cookies",
        servingSize: "2 pieces",
        calories: 120,
        protein: 1.5,
        carbs: 18,
        fat: 5,
        fiber: 0.8,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "chips": {
        name: "Chips",
        servingSize: "1 small packet",
        calories: 150,
        protein: 2,
        carbs: 15,
        fat: 10,
        fiber: 1,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "popcorn": {
        name: "Popcorn",
        servingSize: "1 cup",
        calories: 40,
        protein: 1,
        carbs: 7,
        fat: 1,
        fiber: 1.2,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "sandwich": {
        name: "Sandwich",
        servingSize: "1 grilled veggie",
        calories: 220,
        protein: 6,
        carbs: 35,
        fat: 8,
        fiber: 3,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "burger": {
        name: "Burger",
        servingSize: "1 veggie",
        calories: 380,
        protein: 11,
        carbs: 50,
        fat: 14,
        fiber: 4,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "pizza": {
        name: "Pizza",
        servingSize: "1 slice",
        calories: 250,
        protein: 9,
        carbs: 28,
        fat: 10,
        fiber: 2,
        iron: 2.5,
        calcium: 200,
        vitaminC: 1.2
    },
    "yogurt": {
        name: "Yogurt",
        servingSize: "1 cup",
        calories: 120,
        protein: 6,
        carbs: 10,
        fat: 6,
        fiber: 0,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "paneer": {
        name: "Paneer",
        servingSize: "100g",
        calories: 265,
        protein: 18,
        carbs: 1,
        fat: 20,
        fiber: 0,
        iron: 2.4,
        calcium: 480,
        vitaminC: 0
    },
    "cheese": {
        name: "Cheese",
        servingSize: "1 slice",
        calories: 110,
        protein: 6,
        carbs: 1,
        fat: 9,
        fiber: 0,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "spinach": {
        name: "Spinach",
        servingSize: "1 cup cooked",
        calories: 40,
        protein: 3,
        carbs: 4,
        fat: 0.5,
        fiber: 3,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "drumstick leaves": {
        name: "Drumstick Leaves",
        servingSize: "1 cup cooked",
        calories: 60,
        protein: 5,
        carbs: 8,
        fat: 1.5,
        fiber: 4,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "fenugreek leaves": {
        name: "Fenugreek Leaves",
        servingSize: "1 cup cooked",
        calories: 50,
        protein: 4,
        carbs: 6,
        fat: 1,
        fiber: 3.5,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "amaranth leaves": {
        name: "Amaranth Leaves",
        servingSize: "1 cup cooked",
        calories: 45,
        protein: 3.5,
        carbs: 6,
        fat: 1,
        fiber: 3,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "carrot": {
        name: "Carrot",
        servingSize: "1 medium raw",
        calories: 25,
        protein: 0.5,
        carbs: 6,
        fat: 0.1,
        fiber: 2,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "beetroot": {
        name: "Beetroot",
        servingSize: "1 medium raw",
        calories: 35,
        protein: 1,
        carbs: 8,
        fat: 0.1,
        fiber: 2,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "tomato": {
        name: "Tomato",
        servingSize: "1 medium raw",
        calories: 22,
        protein: 1,
        carbs: 4,
        fat: 0.2,
        fiber: 1.5,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "cucumber": {
        name: "Cucumber",
        servingSize: "1 cup raw slices",
        calories: 16,
        protein: 0.6,
        carbs: 3,
        fat: 0.1,
        fiber: 1,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "beans": {
        name: "Beans",
        servingSize: "1 cup boiled",
        calories: 44,
        protein: 2,
        carbs: 8,
        fat: 0.2,
        fiber: 3,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "cabbage": {
        name: "Cabbage",
        servingSize: "1 cup boiled",
        calories: 33,
        protein: 1.5,
        carbs: 7,
        fat: 0.1,
        fiber: 2.5,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "cauliflower": {
        name: "Cauliflower",
        servingSize: "1 cup boiled",
        calories: 28,
        protein: 2,
        carbs: 5,
        fat: 0.2,
        fiber: 2,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "broccoli": {
        name: "Broccoli",
        servingSize: "1 cup boiled",
        calories: 54,
        protein: 4,
        carbs: 10,
        fat: 0.6,
        fiber: 3.8,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "pumpkin": {
        name: "Pumpkin",
        servingSize: "1 cup cooked",
        calories: 49,
        protein: 1.8,
        carbs: 12,
        fat: 0.2,
        fiber: 3,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    },
    "sweet potato": {
        name: "Sweet Potato",
        servingSize: "1 medium boiled",
        calories: 112,
        protein: 2,
        carbs: 26,
        fat: 0.1,
        fiber: 4,
        iron: 1,
        calcium: 20,
        vitaminC: 1
    }
};

/**
 * Parses the quantity string and returns a scaling factor compared to the base serving size.
 * @param {string} quantityStr - E.g. "2 pieces", "1 bowl", "100g"
 * @param {string} foodName - Normalized food name key
 * @returns {number} Multiplier/scaling factor
 */
export const calculateQuantityMultiplier = (quantityStr, foodName) => {
    if (!quantityStr) return 1.0;
    
    const dbItem = NUTRITION_DB[foodName.toLowerCase().trim()];
    if (!dbItem) return 1.0;

    const qtyLower = quantityStr.toLowerCase();
    const dbQtyLower = dbItem.servingSize.toLowerCase();

    // Extract first numeric value from both
    const qtyMatch = qtyLower.match(/([\d.]+)/);
    const dbQtyMatch = dbQtyLower.match(/([\d.]+)/);

    if (qtyMatch && dbQtyMatch) {
        const qtyNum = parseFloat(qtyMatch[1]);
        const dbQtyNum = parseFloat(dbQtyMatch[1]);
        if (!isNaN(qtyNum) && !isNaN(dbQtyNum) && dbQtyNum > 0) {
            return qtyNum / dbQtyNum;
        }
    }
    return 1.0;
};

/**
 * Calculates nutritional values for a given food name and quantity.
 * @param {string} foodName - Food name
 * @param {string} quantity - E.g. "2 pieces"
 * @returns {object} Nutritional breakdown
 */
export const calculateFoodNutrition = (foodName, quantity = "") => {
    const key = foodName.toLowerCase().trim();
    const dbItem = NUTRITION_DB[key];
    
    // Default fallback values if food is not recognized
    if (!dbItem) {
        return {
            name: foodName,
            quantity: quantity || "1 serving",
            calories: 120,
            protein: 3.0,
            carbs: 18.0,
            fats: 4.0,
            fiber: 1.5,
            iron: 0.8,
            calcium: 20,
            vitaminC: 2.0
        };
    }

    const qty = quantity || dbItem.servingSize;
    const mult = calculateQuantityMultiplier(qty, key);

    return {
        name: dbItem.name || foodName,
        quantity: qty,
        calories: Math.round(dbItem.calories * mult),
        protein: Math.round((dbItem.protein * mult) * 100) / 100,
        carbs: Math.round((dbItem.carbs * mult) * 100) / 100,
        fats: Math.round((dbItem.fat * mult) * 100) / 100,
        fiber: Math.round((dbItem.fiber * mult) * 100) / 100,
        iron: Math.round((dbItem.iron * mult) * 100) / 100,
        calcium: Math.round(dbItem.calcium * mult),
        vitaminC: Math.round((dbItem.vitaminC * mult) * 100) / 100
    };
};
